// Markdown export tree, mirroring the cloud export layout: one .md file per
// published page (section pages become directories), YAML frontmatter, and a
// README.md index. Citation tokens stay verbatim, as in the cloud export.
import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { PageRecord } from "./state.js";

const safe = (value: string) => value.replace(/[^a-z0-9-_]/gi, "-");

export async function exportMarkdown(input: {
  outDir: string;
  repo: { owner: string; name: string };
  commitSha: string;
  pages: PageRecord[];
  markdownOf: (slug: string) => Promise<string | null>;
}): Promise<void> {
  const target = path.join(input.outDir, "markdown");
  await rm(target, { recursive: true, force: true });
  await mkdir(target, { recursive: true });

  const sections = new Map(
    input.pages.filter((p) => p.kind === "section").map((p) => [p.slug, p]),
  );

  for (const page of [...input.pages].sort((a, b) => a.position - b.position)) {
    if (page.kind === "section" || page.status !== "published") continue;
    const markdown = await input.markdownOf(page.slug);
    if (!markdown) continue;
    const section = page.parentSlug == null ? undefined : sections.get(page.parentSlug);
    const directory = section ? `${safe(section.slug)}/` : "";
    const frontMatter = [
      "---",
      `title: "${page.title.replace(/"/g, '\\"')}"`,
      `kind: ${page.kind}`,
      section ? `section: "${section.title.replace(/"/g, '\\"')}"` : null,
      page.commitSha ? `commit: ${page.commitSha}` : null,
      `generated: ${new Date().toISOString()}`,
      "---",
      "",
    ]
      .filter((line): line is string => line !== null)
      .join("\n");
    const file = path.join(target, directory, `${safe(page.slug)}.md`);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, frontMatter + markdown + "\n", "utf8");
  }

  await writeFile(
    path.join(target, "README.md"),
    `# ${input.repo.owner}/${input.repo.name} - Wiki export\n\nGenerated by RepoFold from commit ${input.commitSha}.\n`,
    "utf8",
  );
}
